### ISSUE TITLE
error maybe webpack related?

### ISSUE THREAD

**Issue by pbuckley** [tcbyrd/probot-lambda#10]
I'm seeing the following error when trying to run a stock (unchanged) probot-lambda:
```
message": "module initialization error: Error\n    at Object.<anonymous> (/var/task/node_modules/github/index.js:1:69)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/var/task/handler.js:1603:18)\n    at __webpack_require__ (/var/task/handler.js:20:30)\n    at Object._typeof (/var/task/handler.js:1091:17)\n    at __webpack_require__ (/var/task/handler.js:20:30)\n    at Object.i (/var/task/handler.js:455:19)\n    at __webpack_require__ (/var/task/handler.js:20:30)\n    at Object.<anonymous> (/var/task/handler.js:96:20)\n    at __webpack_require__ (/var/task/handler.js:20:30)\n    at Object.<anonymous> (/var/task/handler.js:1664:18)\n    at __webpack_require__ (/var/task/handler.js:20:30)\n    at /var/task/handler.js:66:18\n    at Object.<anonymous> (/var/task/handler.js:69:10)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n"
```
Seems like it might be webpack related based on the readme? But I've got the unchanged `serverless-webpack` plugin in my serverless.yml, I really haven't made any changes to the code yet and just trying to `sls deploy` as is from my fork of your repo (thanks btw - this project looks like just the thing that I want to use for my github org!)

I'm on OSX 10.12.6, using nvm to manage my node versions. Initially I had node v8.0.0 and got this error:
```
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
```
so I switched to v10.1.0 and can successfully `sls deploy` now, not sure if these warnings are all ok or if they're indicative of any symptoms contributing to my issue(s)?
```
$ sls deploy
(node:20413) ExperimentalWarning: The fs.promises API is experimental
Serverless: Bundling with Webpack...
Time: 996ms
            Asset     Size  Chunks             Chunk Names
  private-key.pem  1.68 kB          [emitted]  
       handler.js  52.8 kB       0  [emitted]  main
 static/robot.svg  6.89 kB          [emitted]  
 views/probot.ejs   1.4 kB          [emitted]  
static/primer.css   116 kB          [emitted]  

WARNING in ./probot/lib/resolver.js
11:9-52 Critical dependency: the request of a dependency is an expression

WARNING in ./probot/lib/plugins/default.js
8:8-57 Critical dependency: the request of a dependency is an expression
Serverless: WARNING: Could not determine version of module express
Serverless: WARNING: Could not determine version of module bottleneck
Serverless: WARNING: Could not determine version of module bunyan
Serverless: WARNING: Could not determine version of module bunyan-format
Serverless: WARNING: Could not determine version of module bunyan-sentry-stream
Serverless: WARNING: Could not determine version of module cache-manager
Serverless: WARNING: Could not determine version of module github
Serverless: WARNING: Could not determine version of module github-app
Serverless: WARNING: Could not determine version of module github-webhook-handler
Serverless: WARNING: Could not determine version of module js-yaml
Serverless: WARNING: Could not determine version of module promise-events
Serverless: WARNING: Could not determine version of module raven
Serverless: WARNING: Could not determine version of module resolve
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: express, babel-polyfill@6.16.0, bottleneck, bunyan, bunyan-format, bunyan-sentry-stream, cache-manager, github, github-app, github-webhook-handler, js-yaml, probot@3.0.0, probot-commands@^1.0.0, promise-events, raven, resolve, serverless-http@^1.5.1
Serverless: WARNING: Could not determine version of module express
Serverless: WARNING: Could not determine version of module bottleneck
Serverless: WARNING: Could not determine version of module bunyan
Serverless: WARNING: Could not determine version of module bunyan-format
Serverless: WARNING: Could not determine version of module bunyan-sentry-stream
Serverless: WARNING: Could not determine version of module cache-manager
Serverless: WARNING: Could not determine version of module github
Serverless: WARNING: Could not determine version of module github-app
Serverless: WARNING: Could not determine version of module github-webhook-handler
Serverless: WARNING: Could not determine version of module js-yaml
Serverless: WARNING: Could not determine version of module promise-events
Serverless: WARNING: Could not determine version of module raven
Serverless: WARNING: Could not determine version of module resolve
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....................................
Serverless: Stack update finished...
Service Information
service: lambda-probot-express
stage: dev
region: us-east-1
stack: lambda-probot-express-dev
api keys:
  None
endpoints:
  GET - https://scrambled.execute-api.region.amazonaws.com/dev/{page+}
  GET - https://scrambled.execute-api.region.amazonaws.com/dev/
  POST - https://scrambled.execute-api.regio.amazonaws.com/dev/
functions:
  router: lambda-probot-express-dev-router
```

**Comment by pbuckley** [comment]
So I got a little further by trying to pin my node deps - I switched to node 6.10.0 locally, blew away `./node_modules`, and removed all the "ranges" from dependencies in package.json, then `npm install` again. The current moment in time also requires that `@octokit/rest` be installed, so I added that to package.json, too (not sure if you'd want a PR for that one?). Now I'm getting an error about bottleneck - still seems to be "node dependency ranges are the work of the devil" related. The error suggests that I have bottleneck v2 somehow, even though I see v1 is getting installed as a dependency of probot.

From my `npm install` locally I see bottleneck 1.x:
```
├─┬ probot@3.0.0 
│ ├── bottleneck@1.16.0 
```

But in the logs of my lambda I see the error about "calling bottleneck v2 in v1 style?"
```
    "events": [
        {
            "ingestionTime": 1526996440911, 
            "timestamp": 1526996440899, 
            "message": "START RequestId: <RID_snipped> Version: $LATEST\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "\\u001b[90m13:40:40.959Z\\u001b[39m \\u001b[31mERROR\\u001b[39m Probot:\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "\\u001b[90m  \\u001b[36mPromise {\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "    <rejected> Error: Bottleneck v2 takes a single object argument. Refer to https://github.com/SGrondin/bottleneck#upgrading-to-v2 if you're upgrading from Bottleneck v1.\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at BottleneckError (/var/task/node_modules/bottleneck/lib/BottleneckError.js:7:21)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at new Bottleneck (/var/task/node_modules/bottleneck/lib/Bottleneck.js:63:17)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at rateLimitedClient (/var/task/handler.js:1382:17)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at probotEnhancedClient (/var/task/handler.js:1372:12)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at Robot._callee3$ (/var/task/handler.js:1350:51)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:337:22)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:96:21)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at step (/var/task/handler.js:1084:191)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at /var/task/handler.js:1084:361\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at process._tickDomainCallback (internal/process/next_tick.js:135:7)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at Module.runMain (module.js:606:11)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at run (bootstrap_node.js:390:7)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at startup (bootstrap_node.js:150:9)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at bootstrap_node.js:505:3 }\\u001b[39m\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "  --\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "  Error: Bottleneck v2 takes a single object argument. Refer to https://github.com/SGrondin/bottleneck#upgrading-to-v2 if you're upgrading from Bottleneck v1.\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at BottleneckError (/var/task/node_modules/bottleneck/lib/BottleneckError.js:7:21)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at new Bottleneck (/var/task/node_modules/bottleneck/lib/Bottleneck.js:63:17)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at rateLimitedClient (/var/task/handler.js:1382:17)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at probotEnhancedClient (/var/task/handler.js:1372:12)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at Robot._callee3$ (/var/task/handler.js:1350:51)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:337:22)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:96:21)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at step (/var/task/handler.js:1084:191)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at /var/task/handler.js:1084:361\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at process._tickDomainCallback (internal/process/next_tick.js:135:7)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at Module.runMain (module.js:606:11)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at run (bootstrap_node.js:390:7)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at startup (bootstrap_node.js:150:9)\n"
        }, 
        {
            "ingestionTime": 1526996440979, 
            "timestamp": 1526996440969, 
            "message": "      at bootstrap_node.js:505:3\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "\\u001b[39m\\u001b[90m13:40:40.974Z\\u001b[39m \\u001b[31mERROR\\u001b[39m Probot:\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "\\u001b[90m  \\u001b[36mPromise {\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "    <rejected> Error: Bottleneck v2 takes a single object argument. Refer to https://github.com/SGrondin/bottleneck#upgrading-to-v2 if you're upgrading from Bottleneck v1.\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at BottleneckError (/var/task/node_modules/bottleneck/lib/BottleneckError.js:7:21)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at new Bottleneck (/var/task/node_modules/bottleneck/lib/Bottleneck.js:63:17)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at rateLimitedClient (/var/task/handler.js:1382:17)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at probotEnhancedClient (/var/task/handler.js:1372:12)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at Robot._callee3$ (/var/task/handler.js:1350:51)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:337:22)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:96:21)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at step (/var/task/handler.js:1084:191)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at /var/task/handler.js:1084:361\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at process._tickDomainCallback (internal/process/next_tick.js:135:7)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at Module.runMain (module.js:606:11)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at run (bootstrap_node.js:390:7)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at startup (bootstrap_node.js:150:9)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at bootstrap_node.js:505:3 }\\u001b[39m\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "  --\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "  Error: Bottleneck v2 takes a single object argument. Refer to https://github.com/SGrondin/bottleneck#upgrading-to-v2 if you're upgrading from Bottleneck v1.\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at BottleneckError (/var/task/node_modules/bottleneck/lib/BottleneckError.js:7:21)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at new Bottleneck (/var/task/node_modules/bottleneck/lib/Bottleneck.js:63:17)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at rateLimitedClient (/var/task/handler.js:1382:17)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at probotEnhancedClient (/var/task/handler.js:1372:12)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at Robot._callee3$ (/var/task/handler.js:1350:51)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:337:22)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:96:21)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at step (/var/task/handler.js:1084:191)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at /var/task/handler.js:1084:361\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at process._tickDomainCallback (internal/process/next_tick.js:135:7)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at Module.runMain (module.js:606:11)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at run (bootstrap_node.js:390:7)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at startup (bootstrap_node.js:150:9)\n"
        }, 
        {
            "ingestionTime": 1526996456034, 
            "timestamp": 1526996440975, 
            "message": "      at bootstrap_node.js:505:3\n"
        },
```

**Comment by pbuckley** [comment]
I made a little more progress, I think - I got past the bottleneck version issue by hackmonkeypatching the robot.js in ./probot (not sure how that gets in the root, or why it gets put there and in ./node_modules but we definitely are using the probot from the root of the repo and not the identical ./node_modules/probot). I changed this line:
`  const limiter = new Bottleneck(1, 1000)`
to use the bottleneck v2 constructor:
`  const limiter = new Bottleneck({maxConcurrent: 1, minTime: 1000})`
So my bottleneck version errors are gone, and now I get no errors... but no action(s), either. I just get a happy log that does nothing now when I create a new issue in my test repo:
```
    "events": [
        {
            "ingestionTime": 1527160930996, 
            "timestamp": 1527160931021, 
            "message": "START RequestId: <numbers> Version: $LATEST\n"
        }, 
        {
            "ingestionTime": 1527160946080, 
            "timestamp": 1527160931065, 
            "message": "\\u001b[90m11:22:11.063Z\\u001b[39m \\u001b[32m INFO\\u001b[39m Probot: \\u001b[36m this.log.info from line 97 of robot.js to show current directory probot is the one called \\u001b[39m\n"
        }, 
        {
            "ingestionTime": 1527160946080, 
            "timestamp": 1527160931076, 
            "message": "END RequestId: <numbers>\n"
        }, 
        {
            "ingestionTime": 1527160946080, 
            "timestamp": 1527160931076, 
            "message": "REPORT RequestId: b2814113-5f44-11e8-a17d-cd6d65e7dbe4\tDuration: 45.70 ms\tBilled Duration: 100 ms \tMemory Size: 1024 MB\tMax Memory Used: 70 MB\t\n"
        }
    ], 
```

**Comment by tcbyrd** [comment]
Closing in favor of the new extension published in the Probot Org that doesn't use babel/webpack: https://github.com/probot/serverless-lambda

Feel free to test that out and open issues over there!
